<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Negative - Test Case</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d44e8cb9-6ac9-40e1-b592-deb918a3b85f</testSuiteGuid>
   <testCaseLink>
      <guid>d7f42feb-48d6-4915-b3c2-9714f7c145a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mobile/TS-Mobile-003- Update Profile/Negative/TCUP011- Cancel Update By Pressing Back</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d97dd583-813e-476e-bb0a-c08a48b9eb3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2021aa99-1304-4d75-af97-f0d76373d684</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce125012-bdfa-4d13-9b98-57deee234643</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mobile/TS-Mobile-003- Update Profile/Negative/TCUP012-Update Name by Adding Number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52768699-1d94-4f0a-b3c5-0f425a050969</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8f214e7-d544-4a71-9354-730b434fd09d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69274e50-37c9-4f76-9151-a98c69568628</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mobile/TS-Mobile-003- Update Profile/Negative/TCUP013-Update Name by Adding Special Characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e3f69cb-902c-4f2a-b2cc-8c28ecd58742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7472e148-28dc-4a4f-943b-d0f6ef6f4497</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43cc5568-56cc-47dc-872b-d97fc621b94b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mobile/TS-Mobile-003- Update Profile/Negative/TCUP018- Update Phone Number with 8 Characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>18af5bb5-2887-4af8-bedb-39b317d734e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mobile/TS-Mobile-003- Update Profile/Negative/TCUP019- Update Phone Number with 14 Characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
