<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Lihat Event Lainnya</name>
   <tag></tag>
   <elementGuidId>aa6881ec-7d97-421b-aefd-462868eb3956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='eventLainnya']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eventLainnya</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1457e720-b0b6-436f-bc10-1e8f5c56b081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/event</value>
      <webElementGuid>377a55ee-84f5-4042-9b71-bd474c4c4d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventLainnya</value>
      <webElementGuid>d6b063f0-8de5-435a-b5c7-76464ac027c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lihat Event Lainnya</value>
      <webElementGuid>128b90ce-a44f-440b-9329-4193945b8dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventLainnya&quot;)</value>
      <webElementGuid>5277ecc9-9e5c-4de4-a3e8-2ca0eda935c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='eventLainnya']</value>
      <webElementGuid>1b6a2d4a-b18c-4507-95bd-8754f60d62bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal_Success']/div/div[2]/a[2]</value>
      <webElementGuid>7557efab-abff-40fc-b30b-3e01d6873065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Event Lainnya')]</value>
      <webElementGuid>b42491cd-3719-40d5-b156-5ef631f2f70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day 3: Predict using Machine Learning'])[3]/following::a[2]</value>
      <webElementGuid>ce0a3904-72d9-4e47-bd74-cd899e1f73a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2010-2021 Coding.ID All rights reserved.'])[1]/preceding::a[1]</value>
      <webElementGuid>91938e7a-6abb-4ae5-af8b-9d282aff44bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course'])[4]/preceding::a[6]</value>
      <webElementGuid>f92055a7-b837-4b8f-83dc-86ddf2754d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Event Lainnya']/parent::*</value>
      <webElementGuid>d1b7f160-83c2-40d6-905c-0700b87f20c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/event')])[10]</value>
      <webElementGuid>6d68e83d-12ed-43d9-a87d-ca67ee17c14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/a[2]</value>
      <webElementGuid>a9d1cc0f-b70f-4731-8275-dfcbd648205a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/event' and @id = 'eventLainnya' and (text() = ' Lihat Event Lainnya' or . = ' Lihat Event Lainnya')]</value>
      <webElementGuid>15149890-54f1-49fb-bc2c-2d7057175d87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
